// import Head from 'next/head'
// import Image from 'next/image'
// import Link from 'next/link';
// import { Inter } from 'next/font/google'
// import { Layout, Button, Row, Col } from 'antd';
// import logo from './../public/images/logo.png'
// import profile from './../public/images/profile.jpg'
// import styles from '@/styles/Home.module.css'
// // import { Parallax } from 'rc-scroll-anim';

// const inter = Inter({ subsets: ['latin'] })
// const { Header, Footer, Content } = Layout;

export default function Home() {
  return <>HI</>
}

// export default function Home() {
//   return (
//     <>
//       <Head>
//         <title>だんだん</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <Layout>
//         {/* -------------------- Navigation Bar ------------------------------ */}
//         <Header className={styles.headerStyle}>
//           <Image  alt='' height={50} src={logo} />
//           <div>
//             <Link className={styles.bttnSpace} href={'/home/'}>Login</Link>
//             <Link className={styles.bttnSpace} href={'/register/'}>Register</Link>
//           </div>
//         </Header>
//         {/* -------------------- Hero Section ------------------------------ */}
//         <div className={styles.landing}> 
//          This is my landing section
//           <div className={styles.box}></div>
//         </div>
//         <div className={styles.grassAni}></div>
//         {/* -------------------- Main Body Section ------------------------------ */}
//         <Content className={styles.contentStyle}>
//           <Row className={styles.rowStyle}>
//             <Col className={styles.colStyle} span={6}><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris at tincidunt augue, semper accumsan risus. 
//             Nullam faucibus mauris ex. Etiam eu tincidunt justo, ac aliquet ligula. Donec lobortis accumsan lacinia. 
//             Vivamus viverra, enim at blandit sodales, ligula mi pellentesque urna, eu commodo sem nisi at sem. Phasellus 
//             dignissim interdum cursus.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris at tincidunt augue, semper accumsan risus. 
//             Nullam faucibus mauris ex. Etiam eu tincidunt justo, ac aliquet ligula. Donec lobortis accumsan lacinia. 
//             Vivamus viverra, enim at blandit sodales, ligula mi pellentesque urna, eu commodo sem nisi at sem. Phasellus 
//             dignissim interdum cursus.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris at tincidunt augue, semper accumsan risus. 
//             Nullam faucibus mauris ex. Etiam eu tincidunt justo, ac aliquet ligula. Donec lobortis accumsan lacinia. 
//             Vivamus viverra, enim at blandit sodales, ligula mi pellentesque urna, eu commodo sem nisi at sem. Phasellus 
//             dignissim interdum cursus.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris at tincidunt augue, semper accumsan risus. 
//             Nullam faucibus mauris ex. Etiam eu tincidunt justo, ac aliquet ligula. Donec lobortis accumsan lacinia. 
//             Vivamus viverra, enim at blandit sodales, ligula mi pellentesque urna, eu commodo sem nisi at sem. Phasellus 
//             dignissim interdum cursus.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris at tincidunt augue, semper accumsan risus. 
//             Nullam faucibus mauris ex. Etiam eu tincidunt justo, ac aliquet ligula. Donec lobortis accumsan lacinia. 
//             Vivamus viverra, enim at blandit sodales, ligula mi pellentesque urna, eu commodo sem nisi at sem. Phasellus 
//             dignissim interdum cursus.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris at tincidunt augue, semper accumsan risus. 
//             Nullam faucibus mauris ex. Etiam eu tincidunt justo, ac aliquet ligula. Donec lobortis accumsan lacinia. 
//             Vivamus viverra, enim at blandit sodales, ligula mi pellentesque urna, eu commodo sem nisi at sem. Phasellus 
//             dignissim interdum cursus.</p></Col>
//             <Col className={styles.colStyle} span={16}><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris at tincidunt augue, semper accumsan risus. 
//             Nullam faucibus mauris ex. Etiam eu tincidunt justo, ac aliquet ligula. Donec lobortis accumsan lacinia. 
//             Vivamus viverra, enim at blandit sodales, ligula mi pellentesque urna, eu commodo sem nisi at sem. Phasellus 
//             dignissim interdum cursus.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris at tincidunt augue, semper accumsan risus. 
//             Nullam faucibus mauris ex. Etiam eu tincidunt justo, ac aliquet ligula. Donec lobortis accumsan lacinia. 
//             Vivamus viverra, enim at blandit sodales, ligula mi pellentesque urna, eu commodo sem nisi at sem. Phasellus 
//             dignissim interdum cursus.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris at tincidunt augue, semper accumsan risus. 
//             Nullam faucibus mauris ex. Etiam eu tincidunt justo, ac aliquet ligula. Donec lobortis accumsan lacinia. 
//             Vivamus viverra, enim at blandit sodales, ligula mi pellentesque urna, eu commodo sem nisi at sem. Phasellus 
//             dignissim interdum cursus.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris at tincidunt augue, semper accumsan risus. 
//             Nullam faucibus mauris ex. Etiam eu tincidunt justo, ac aliquet ligula. Donec lobortis accumsan lacinia. 
//             Vivamus viverra, enim at blandit sodales, ligula mi pellentesque urna, eu commodo sem nisi at sem. Phasellus 
//             dignissim interdum cursus.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris at tincidunt augue, semper accumsan risus. 
//             Nullam faucibus mauris ex. Etiam eu tincidunt justo, ac aliquet ligula. Donec lobortis accumsan lacinia. 
//             Vivamus viverra, enim at blandit sodales, ligula mi pellentesque urna, eu commodo sem nisi at sem. Phasellus 
//             dignissim interdum cursus.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris at tincidunt augue, semper accumsan risus. 
//             Nullam faucibus mauris ex. Etiam eu tincidunt justo, ac aliquet ligula. Donec lobortis accumsan lacinia. 
//             Vivamus viverra, enim at blandit sodales, ligula mi pellentesque urna, eu commodo sem nisi at sem. Phasellus 
//             dignissim interdum cursus.</p></Col>
//           </Row>
//           <Row className={styles.rowStyle}>
//             <Col className={styles.colStyle} span={16}><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris at tincidunt augue, semper accumsan risus. 
//             Nullam faucibus mauris ex. Etiam eu tincidunt justo, ac aliquet ligula. Donec lobortis accumsan lacinia. 
//             Vivamus viverra, enim at blandit sodales, ligula mi pellentesque urna, eu commodo sem nisi at sem. Phasellus 
//             dignissim interdum cursus.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris at tincidunt augue, semper accumsan risus. 
//             Nullam faucibus mauris ex. Etiam eu tincidunt justo, ac aliquet ligula. Donec lobortis accumsan lacinia. 
//             Vivamus viverra, enim at blandit sodales, ligula mi pellentesque urna, eu commodo sem nisi at sem. Phasellus 
//             dignissim interdum cursus.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris at tincidunt augue, semper accumsan risus. 
//             Nullam faucibus mauris ex. Etiam eu tincidunt justo, ac aliquet ligula. Donec lobortis accumsan lacinia. 
//             Vivamus viverra, enim at blandit sodales, ligula mi pellentesque urna, eu commodo sem nisi at sem. Phasellus 
//             dignissim interdum cursus.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris at tincidunt augue, semper accumsan risus. 
//             Nullam faucibus mauris ex. Etiam eu tincidunt justo, ac aliquet ligula. Donec lobortis accumsan lacinia. 
//             Vivamus viverra, enim at blandit sodales, ligula mi pellentesque urna, eu commodo sem nisi at sem. Phasellus 
//             dignissim interdum cursus.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris at tincidunt augue, semper accumsan risus. 
//             Nullam faucibus mauris ex. Etiam eu tincidunt justo, ac aliquet ligula. Donec lobortis accumsan lacinia. 
//             Vivamus viverra, enim at blandit sodales, ligula mi pellentesque urna, eu commodo sem nisi at sem. Phasellus 
//             dignissim interdum cursus.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris at tincidunt augue, semper accumsan risus. 
//             Nullam faucibus mauris ex. Etiam eu tincidunt justo, ac aliquet ligula. Donec lobortis accumsan lacinia. 
//             Vivamus viverra, enim at blandit sodales, ligula mi pellentesque urna, eu commodo sem nisi at sem. Phasellus 
//             dignissim interdum cursus.</p></Col>
//             <div className={styles.imgSide}></div>
//             <Col className={styles.colStyle} span={6}>
//               {/* <Parallax
//                animation={{ opacity:1 }}
//                style={{opacity:0 }}
//                ><Image  alt='' id='myImg' height={250} src={profile}/></Parallax> */}
//             </Col>
//           </Row> 
//           <div className={styles.space}></div>        
//         </Content>
//         {/* -------------------- Footer Section ------------------------------ */}
//         <Footer className={styles.footerStyle}>
//           <Row>
//             {/* <Col span={8}>temp</Col> */}
//             {/* <Col span={8}>temp</Col> */}
//             <Col span={8} offset={8} >temp</Col>
//             <Col span={8}>
//               <h3>Connect with Me</h3>
//               <ul>
//                 <li>Github</li>
//                 <li>LinkedIN</li>
//               </ul>
//             </Col>
//           </Row>
//           <Image  alt='' height={60} className={styles.footerImg} src={logo}/>
//         </Footer>
//       </Layout>
//     </>
//   )
// }
